# Generated by Django 3.2.10 on 2023-10-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='is_palindrome',
            field=models.BooleanField(default=False),
        ),
    ]
