# Generated by Django 3.2.10 on 2023-10-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0002_auto_20231023_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='board',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
