# Generated by Django 3.2.10 on 2023-10-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0003_alter_game_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date_created',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
