# Generated by Django 3.2.10 on 2023-10-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0004_game_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='updated',
            field=models.IntegerField(default=0),
        ),
    ]
