# Generated by Django 3.2.10 on 2023-10-23 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0005_game_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='updated',
            new_name='times_updated',
        ),
    ]
