# Generated by Django 3.2.10 on 2023-10-23 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0006_rename_updated_game_times_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='times_updated',
        ),
    ]
